Adding media to feeds
haseebuchiha/deltabook_FE pull request #5
Opened 2023-08-11 12:07 UTC by SaboohTaha

Added option to add media (images/videos) while creating new feed
On edit page you can add or remove media files
Created a slider to view multiple media in a feed

2023-08-11 15:14 UTC, haseebuchiha requested changes

2023-08-11 15:14 UTC, haseebuchiha commented on src/components/Feed/Edit.jsx
> +        const url = `http://127.0.0.1:3000/api/v1/feeds/${id}`
```suggestion
        const url = `${import.meta.env.BASE_URL}/api/v1/feeds/${id}`
```
Move localhost:3000 address to .env

2023-08-11 15:14 UTC, haseebuchiha commented on src/components/Feed/Edit.jsx
> +                console.log(resp)
remove log

2023-08-11 15:14 UTC, haseebuchiha commented on src/components/Feed/Edit.jsx
> +            .catch(resp => { console.log(resp) })
remove log

2023-08-11 15:14 UTC, haseebuchiha commented on src/components/Feed/Feed.jsx
> +                console.log(resp.data)
remove log

2023-08-11 15:14 UTC, haseebuchiha commented on src/components/Feed/Feed.jsx
> +    function get_url_extension(url) {
Keep function definitions same

2023-08-11 15:14 UTC, haseebuchiha commented on src/components/Feed/Feed.jsx
> +                </div>}
```suggestion
                        imgFormats?.includes(get_url_extension(item.link))) ?
                            <div key={item.blob_id} className="media flex items-center justify-center w-full h-full -translate-x-1/2 absolute transition-all ease-in-out duration-700" style={{ left: `${(index - currMed) * 100 + 50}%` }}>
                                <img className='object-contain max-h-full max-w-full w-full' src={item.link} />
                            </div>
                        }
                        : (vidFormats?.includes(get_url_extension(item.link))) {
                            return <div key={item.blob_id} className="media flex items-center justify-center w-full h-full -translate-x-1/2 absolute transition-all ease-in-out duration-700" style={{ left: `${(index - currMed) * 100 + 50}%` }}>
                                <ReactPlayer url={item.link} className='object-contain max-h-full max-w-full w-full' width="80%" style={{ left: `${(index - currMed) * 100 + 50}%` }} controls />
                            </div>
                        }
                    })}
                </div>}
```

partial comment

2023-08-11 15:14 UTC, haseebuchiha commented on src/components/Feed/Feed.jsx
> +
why so many empty spaces

2023-08-11 15:14 UTC, haseebuchiha commented on src/components/Feed/Form.jsx
> +            media = document.querySelectorAll(".media")
useRef

2023-08-11 15:14 UTC, haseebuchiha commented on src/components/Feed/Form.jsx
> +
use consistent function naming

2023-08-11 15:14 UTC, haseebuchiha commented on src/components/Feed/Form.jsx
> +                    {props.feed.media.map((item, index) => {
make use of turnary operators

2023-08-11 15:14 UTC, haseebuchiha commented on src/components/Feed/New.jsx
> +        setFeed(Object.assign({}, feed, { [e.target.name]: e.target.value }))
```suggestion
        setFeed( {...feed, [e.target.name]: e.target.value})
```

2023-08-11 15:14 UTC, haseebuchiha commented on src/components/Feed/New.jsx
> +            .catch(resp => { console.log(resp) })
log

2023-08-11 15:14 UTC, haseebuchiha commented on src/components/Feeds/Feed.jsx
> +    }
Use consistent function naming

2023-08-11 15:14 UTC, haseebuchiha commented on src/components/Feeds/Feed.jsx
> +                {props.attributes.media.map((item, index) => {
turnary

2023-08-11 15:14 UTC, haseebuchiha commented on src/components/Feeds/Feeds.jsx
> +                console.log(resp.data)
log

2023-08-11 15:14 UTC, haseebuchiha commented on src/components/Feeds/Feeds.jsx
> +    })
```suggestion
    const grid = feedsArr.map((item, index) => 
        (
            <Feed
                key={item.id}
                attributes={item}
                index={index}
                handleDestroy={handleDestroy}
            />)
    )
```

2023-08-11 15:14 UTC, haseebuchiha commented on src/components/Navbar.jsx
> +                      if (item.hasOwnProperty('subitems'))
tunary

2023-08-17 17:24 UTC, SaboohTaha commented
Kindly review my code now after I have added requested changes

2023-08-17 22:15 UTC, haseebuchiha reviewed
Please resolve conflicts in code.

2023-08-18 14:16 UTC, haseebuchiha approved these changes

2023-08-18 14:16 UTC, merged